### ISSUE TITLE
Connector/Gspro 

### ISSUE THREAD

**Issue by Bobbybackspin2** [springbok/MLM2PRO-GSPro-Connector#133] opened 2024-11-13 20:35 UTC
I'm having to open your connector with putting and LM  going green.
But Gspro does not connect. It shows red
I have to manually open Gspro connector for it to show up as open in your connector. 
I'm Bobbybackspin2 on Discord 
Thanks

**Comment by springbok** [comment] 2024-11-13 20:58
Yep a known issue, the initial problem caused by gspro API opening then closing, latest version of gspro fixes that issue but if you now run gspro.exe it no longer displays the display config window, causing an issue. Should have a release in the next day or so that handles these changes.

**Comment by Bobbybackspin2** [comment] 2024-11-13 22:30
I'm using the newest V3 of Gspro now. So I'll keep starting the Gspro connector 1st the SP connector 

⁣Get BlueMail for Android ​

**Comment by iamcdn** [comment] 2024-11-17 20:54
Same issue.  Cant get GsPro to connect with mevo+. Webcam connected.  Mevo connected.  Get api error went trying gspro.  
Tried GsPro first, last, launching GsPro connect but that launches fs connector 

Anyway to keep and see if that api is running. Setting I am missing?

**Comment by springbok** [comment] 2024-11-17 22:06
Are you auto starting gspro, if so manually start it before the connector for now. There will be an update released shortly addressing this issue.

**Comment by iamcdn** [comment] 2024-11-18 00:29
> Are you auto starting gspro, if so manually start it before the connector for now. There will be an update released shortly addressing this issue.
> 
> 
> 
> Sent from my iPhone
> 
> 
> 
> > On 18 Nov 2024, at 7:54 am, iamcdn ***@***.***> wrote:
> 
> > 
> 
> > ﻿
> 
> > Same issue. Cant get GsPro to connect with mevo+. Webcam connected. Mevo connected. Get api error went trying gspro.
> 
> > Tried GsPro first, last, launching GsPro connect but that launches fs connector
> 
> > 
> 
> > Anyway to keep and see if that api is running. Setting I am missing?
> 
> > 
> 
> > —
> 
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > You are receiving this because you commented.
> 
> 

Tried manual via GsPro.exe and launcher. 

Tried release .10
Also GsPro 3.0.1.6

**Comment by Bobbybackspin2** [comment] 2024-11-18 07:02
That's what I'm doing.

⁣Get BlueMail for Android ​

**Comment by springbok** [comment] 2024-11-26 01:39
V1.04.16 should now correctly launch GSPro V3.

**Closed by springbok** 2024-11-26 01:39 UTC
